import {
  AlarmClock,
  Binary,
  Calendar,
  CheckCircle,
  Radio,
  Sheet,
  Text,
  Upload,
} from "lucide-react";

export const inputFields = [
  {
    id: 1,
    name: "Short text",
    type: "text",
    icon: Text,
    question: "",
    required: false,
    static: false,
  },
  {
    id: 2,
    name: "Long text",
    type: "text",
    icon: Text,
    question: "",
    required: false,
    static: false,
  },
  {
    id: 50,
    name: "Number",
    type: "number",
    icon: Binary,
    question: "",
    required: false,
    static: false,
  },
  {
    id: 3,
    name: "Single Select",
    type: "select",
    icon: Radio,
    question: "",
    required: false,
    static: false,
  },
  {
    id: 4,
    name: "Multi Select",
    type: "select",
    icon: CheckCircle,
    question: "",
    required: false,
    static: false,
  },
  {
    id: 5,
    name: "Dropdown",
    type: "dropdown",
    icon: Radio,
  },

  {
    id: 7,
    name: "Date Picker",
    type: "date",
    icon: Calendar,
    question: "",
    required: false,
    static: false,
  },
  {
    id: 8,
    name: "Time",
    type: "time",
    icon: AlarmClock,
  },
  {
    id: 9,
    name: "Upload",
    type: "file",
    icon: Upload,
  },
  {
    id: 11,
    name: "Tables",
    icon: Sheet,
    type: "input",
    columns: [
      {
        id: "col-000",
        name: "Column 1",
        columnType: "",
        inputType: "",
        inputTypeName: "",
      },
    ],
    rows: [{ id: "row-000", data: [{ "Column 1": "" }] }],
  },
];
