'use client';

// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js';

import _cashFlow from './cashFlow.bones.json';
import _dashboard from './dashboard.bones.json';
import _trialBalance from './trialBalance.bones.json';

registerBones({
  cashFlow: _cashFlow,
  dashboard: _dashboard,
  trialBalance: _trialBalance,
});
